-- DROP DATABASE
DROP DATABASE IF EXISTS ecommerce_db;

-- CREATE DATABASE
CREATE DATABASE ecommerce_db;

USE ecommerce_db

CREATE TABLE category (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  category_name VARCHAR(30) UNIQUE NOT NULL
);

CREATE TABLE product (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  product_name VARCHAR(30) UNIQUE NOT NULL,
  price DECIMAL (8,2) UNSIGNED NOT NULL,
  stock INT (10) NOT NULL,
  category_id UNSIGNED NOT NULL,
  INDEX category_ind (category_id)
);

CREATE TABLE tag (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  tag_name VARCHAR(30) UNIQUE NOT NULL
);

CREATE TABLE product_tag (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  product_id VARCHAR(30) UNIQUE NOT NULL,
  INDEX product_ind (product_id),
  tag_id VARCHAR(30) UNIQUE NOT NULL,
  INDEX tag_ind (tag_id)
);